name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        
          node-version: '14'

        
      - name: Install node packages
            run: npm install
            
      - name: Check lint
        run: npm run check:lint
        
      - name: Check prettier
        run: npm run check:prettier
      
      - name: Build
        run: npm run build